### ISSUE TITLE
git-bash issues

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/afp-cli#11]
I am using git-bash as both `bash` and `cmd` and got my Python from miniconda and it is Version `Python 2.7.10 :: Continuum Analytics, Inc.`. I installed `afp-cli` from PyPi and get the following errors:

```
$ afp
Traceback (most recent call last):
  File "c:\users\vhaenel\appdata\local\continuum\miniconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\vhaenel\appdata\local\continuum\miniconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\VHaenel\AppData\Local\Continuum\Miniconda\Scripts\afp.exe\__main__.py", line 9, in <module>
  File "c:\users\vhaenel\appdata\local\continuum\miniconda\lib\site-packages\afp_cli\cli.py", line 189, in main
    password = get_password(username)
  File "c:\users\vhaenel\appdata\local\continuum\miniconda\lib\site-packages\afp_cli\cli.py", line 46, in get_password
    return getpass.getpass("Password for {0}: ".format(username))
  File "c:\users\vhaenel\appdata\local\continuum\miniconda\lib\getpass.py", line 95, in win_getpass
    msvcrt.putch(c)
TypeError: must be char, not unicode


```

**Comment by esc** [comment]
![screenshot-afp](https://cloud.githubusercontent.com/assets/41563/10162974/b69c9470-66af-11e5-8050-a3c7abc2dd87.png)

**Comment by esc** [comment]
The culprit is again the line:

```
from __future__ Import unicode
```

If we remove that it works again.
