### ISSUE TITLE
Handle special characters in role name

### ISSUE THREAD

**Issue by mriehl** [ImmobilienScout24/afp-cli#43]
``` bash
» afpv2 show account-name role-namé
Password for mriehl: 
Traceback (most recent call last):
  File "/usr/local/bin/afpv2", line 9, in <module>
    load_entry_point('afp-cli==1.3.1.post166', 'console_scripts', 'afpv2')()
  File "/usr/local/lib/python2.7/dist-packages/afp_cli/cliv2.py", line 59, in main
    unprotected_main()
  File "/usr/local/lib/python2.7/dist-packages/afp_cli/cliv2.py", line 107, in unprotected_main
    aws_credentials = get_aws_credentials(federation_client, account, role)
  File "/usr/local/lib/python2.7/dist-packages/afp_cli/cli_functions.py", line 60, in get_aws_credentials
    aws_credentials = federation_client.get_aws_credentials(account, role)
  File "/usr/local/lib/python2.7/dist-packages/afp_cli/client.py", line 49, in get_aws_credentials
    role))
  File "/usr/local/lib/python2.7/dist-packages/afp_cli/client.py", line 38, in call_api
    self.api_url, url_suffix, api_result.json()['message']))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 78: ordinal not in range(128)
```

**Comment by schlomo** [comment]
This is an enhancement till we encounter the wirst role with such a name.

**Comment by karolyi** [comment]
Done in https://github.com/ImmobilienScout24/afp-cli/pull/47
