### ISSUE TITLE
Incorrect password doesnt yield useful error message

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/afp-cli#5]
```
zsh» afp --user=vhaenel
Password for vhaenel: 
Traceback (most recent call last):
  File "/data/home/vhaenel/anaconda/envs/afp/lib/python3.5/site-packages/afp_cli/cli.py", line 216, in main
    federation_client.print_account_and_role_list()
  File "/data/home/vhaenel/anaconda/envs/afp/lib/python3.5/site-packages/afp_cli/client.py", line 52, in print_account_and_role_list
    accounts_and_roles = sorted(self.get_account_and_role_list().items())
  File "/data/home/vhaenel/anaconda/envs/afp/lib/python3.5/site-packages/afp_cli/client.py", line 36, in get_account_and_role_list
    accounts_and_roles = self.call_api("/account")
  File "/data/home/vhaenel/anaconda/envs/afp/lib/python3.5/site-packages/afp_cli/client.py", line 28, in call_api
    self.api_url, url_suffix, api_result.status_code, api_result.reason))
Exception: API call to AWS (https://{HOST}/afp-api/latest//account) failed: 401 Authorization Required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/vhaenel/anaconda/envs/afp/bin/afp", line 9, in <module>
    load_entry_point('afp-cli==1.0.6.post0', 'console_scripts', 'afp')()
  File "/data/home/vhaenel/anaconda/envs/afp/lib/python3.5/site-packages/afp_cli/cli.py", line 218, in main
    error("Failed to get account list from AWS: %s" % exc)
  File "/data/home/vhaenel/anaconda/envs/afp/lib/python3.5/site-packages/afp_cli/cli.py", line 35, in error
    print >>sys.stderr, message
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
```

NB: I replaced the real host with `{HOST}`.

**Comment by esc** [comment]
I recently tried this again and received: 

```
Failed to get account list from AWS: API call to AWS (https://afp/afp-api/latest//account) failed: 401 Authorization Required
```

So, closing this as it appears to be fixed.
