### ISSUE TITLE
Using OSX Keyring fails with "Can't fetch password from system"

### ISSUE THREAD

**Issue by kaeff** [ImmobilienScout24/afp-cli#65]
I've tried using the `--password-provider` option on OSX 10.11.5. I can store the password, but every subsequent invocation of afp fails with the error _"Can't fetch password from system"_:

``` bash
$  afp --password-provider keyring accountname                                                                                                                                                              ✭
No password found in keychain, please enter it now to store it.
Password for kaeffetter:
Entering AFP subshell for account accountname, role full-access.
Press CTRL+D to exit.
bash: git_prompt_info: command not found
(AWS accountname/full-access 59 Min) (cfn-sphere)%{[red]%}➜ %{[green]%}%p %{[cyan]%}%c %{[blue]%}%{[blue]%} % %{%}exit
Left AFP subshell.
```

Works: The keychain now contains an entry called "afp".

``` bash
$  afp --password-provider keyring accountname                                                                                                                                                              ✭
Traceback (most recent call last):
  File "/Users/kaeff/.virtualenvs/cfn-sphere/bin/afp", line 10, in <module>
    main()
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/afp_cli/cli.py", line 50, in main
    unprotected_main()
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/afp_cli/cli.py", line 74, in unprotected_main
    password = get_password(password_provider, username)
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/afp_cli/password_providers.py", line 61, in get_password
    password = keyring_get_password(username)
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/afp_cli/password_providers.py", line 49, in keyring_get_password
    password = keyring.get_password('afp', username)
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/keyring/backends/OS_X.py", line 44, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 92, in find_generic_password
    NotFound.raise_for_status(status, msg)
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 43, in raise_for_status
    Error.raise_for_status(status, msg)
  File "/Users/kaeff/.virtualenvs/cfn-sphere/lib/python2.7/site-packages/keyring/backends/_OS_X_API.py", line 35, in raise_for_status
    raise cls(status, msg)
keyring.backends._OS_X_API.Error: (-25293, "Can't fetch password from system")
```

Fails.

The configuration file contains `user` and `api_url` entries.

**Comment by esc** [comment]
my guess is that this is an issue with the `keyring` module. Perhaps you could use that in isolation to reproduce the error and confirm it has nothing to do with `afp-cli`?

**Comment by esc** [comment]
https://pypi.python.org/pypi/keyring <-- here it is, it has a command-line application too, maybe that will help.

**Comment by kaeff** [comment]
Yes, it is this issue: https://github.com/jaraco/keyring/issues/219. The keyring cli has the same problem on my machine.

As suggested in the root issue, downgrading keyring in the virtualenv fixes the issue, also for afp-cli:

`pip install keyring==8.7`

Thanks!

**Comment by esc** [comment]
Sweet, can you close the issue.
